name: Student Feedback CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check HTML
        run: test -f index.html

      - name: Check CSS
        run: test -f style.css

      - name: Check JavaScript
        run: test -f script.js

      - name: Validate JavaScript
        run: node --check script.js